[tool.poetry]
name = "rsi-divergence"
version = "0.1.0"
description = "A complete, industry-grade RSI divergence detector."
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
numpy = "^1.23.5"
pandas = "^1.5.2"
scipy = "^1.10.0"
numba = "^0.56.4"
typer = {extras = ["all"], version = "^0.7.0"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
hypothesis = "^6.58.0"
mypy = "^0.991"
black = "^22.12.0"
flake8 = "^6.0.0"
sphinx = "^5.3.0"

[tool.poetry.scripts]
rsi_divergence = "rsi_divergence.cli:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.mypy]
ignore_missing_imports = true
