# This workflow will upload a Python Package using trusted publishing

name: Upload Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/rsi-divergence-detector

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Build sdist and wheel using PEP 517 "build" (no Poetry involved)
    - name: Build package
      run: |
        python -m pip install --upgrade pip build
        python -m build

    # Publish the artifacts in ./dist/ to Test PyPI
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
